[package]
name = "hoosecalc"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust_decimal_macros = "1.14"

[dependencies.rust_decimal]
version = "1.14.3"

[dev-dependencies]
